# Generated by Django 5.0.1 on 2024-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=100)),
                ("level", models.IntegerField()),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("Beans and Stew", "Beans and Stew"),
                            ("Cereal and Bread", "Cereal and Bread"),
                            ("Cupcake", "Cupcake"),
                            ("Custard", "Custard"),
                            ("Eba", "Eba"),
                            ("Egusi soup", "Egusi soup"),
                            ("Fried rice", "Fried rice"),
                            ("Garri", "Garri"),
                            ("Fried potato and Eggsauce", "Fried potato and Eggsauce"),
                            ("Jollef Rice", "Jollef Rice"),
                            ("Jollef Spaghetti", "Jollef Spaghetti"),
                            ("Moi Moi", "Moi Moi"),
                            ("Okra soup", "Okra soup"),
                            ("Pap", "Pap"),
                            ("Plantain and Eggsauce", "Plantain and Eggsauce"),
                            ("Porrage Beans", "Porrage Beans"),
                            ("Porrage Yam", "Porrage Yam"),
                            ("Pounded yam", "Pounded yam"),
                            ("Semo", "Semo"),
                            ("Spaghetti and Egg sauce", "Spaghetti and Egg sauce"),
                            ("Spaghetti and Stew", "Spaghetti and Stew"),
                            ("Wheat Bread", "Wheat Bread"),
                            ("White rice and Gbadun", "White rice and Gbadun"),
                            ("White rice and Red stew", "White rice and Red stew"),
                            ("Yam and Egg sauce", "Yam and Egg sauce"),
                            ("Yam and Stew", "Yam and Stew"),
                            ("Zobo", "Zobo"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very poor"),
                            (2, "Poor"),
                            (3, "Fair"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
            ],
        ),
    ]
