# Generated by Django 5.0.2 on 2024-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='meal',
            field=models.CharField(choices=[('Beans and stew with bread/garri', 'Beans and stew with bread/garri'), ('Cereal and Bread', 'Cereal and Bread'), ('Sabath meal', 'Sabath meal'), ('Swallow and Ewedu soup', 'Swallow and Ewedu soup'), ('Swallow and Egusi soup', 'Swallow and Egusi soup'), ('Swallow and Okra soup', 'Swallow and Okra soup'), ('Fried rice', 'Fried rice'), ('Fried potato and Eggsauce', 'Fried potato and Eggsauce'), ('Jollef Rice', 'Jollef Rice'), ('Jollof Spaghetti', 'Jollof Spaghetti'), ('Moi Moi', 'Moi Moi'), ('Pap/custard/oats and Akara', 'Pap/custard/oats and Akara'), ('Plantain and Eggsauce', 'Plantain and Eggsauce'), ('Plantain and Stew', 'Plantain and Stew'), ('Porridge Beans', 'Porridge Beans'), ('Porridge Yam', 'Porridge Yam'), ('Spaghetti and Egg sauce', 'Spaghetti and Egg sauce'), ('Spaghetti and Stew', 'Spaghetti and Stew'), ('White rice and gbadun stew', 'White rice and gbadun stew'), ('White rice and red stew', 'White rice and red stew'), ('Yam and Egg sauce', 'Yam and Egg sauce'), ('Yam and Stew', 'Yam and Stew')], max_length=100),
        ),
    ]
